# Generated by Django 4.0.3 on 2022-07-04 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FSAEDesigner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeometryDesignerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('is_public', models.BooleanField(default=False, verbose_name='public')),
                ('content', models.TextField(verbose_name='content')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'GeometryDesignerFile',
                'verbose_name_plural': 'GeometryDesignerFile',
            },
        ),
    ]
