# Generated by Django 4.0.3 on 2022-07-05 14:34

import FSAEDesigner.models
from django.db import migrations, models
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('FSAEDesigner', '0002_geometrydesignerfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geometrydesignerfile',
            name='updated',
        ),
        migrations.AddField(
            model_name='geometrydesignerfile',
            name='lastUpdated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last updated'),
        ),
        migrations.AddField(
            model_name='geometrydesignerfile',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=FSAEDesigner.models.GeometryDesignerFile.get_image_path),
        ),
    ]
