# Generated by Django 4.0.3 on 2022-07-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FSAEDesigner', '0003_remove_geometrydesignerfile_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geometrydesignerfile',
            name='note',
            field=models.CharField(blank=True, max_length=4096, verbose_name='note'),
        ),
    ]
